2021-09-22 00:18:29,922 INFO    MainThread:245296 [wandb_setup.py:_flush():69] setting env: {}
2021-09-22 00:18:29,922 INFO    MainThread:245296 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-22 00:18:29,922 INFO    MainThread:245296 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/RNN/Weather-archive-Jena/wandb/run-20210922_001829-19hehbmw/logs/debug.log
2021-09-22 00:18:29,922 INFO    MainThread:245296 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/RNN/Weather-archive-Jena/wandb/run-20210922_001829-19hehbmw/logs/debug-internal.log
2021-09-22 00:18:29,922 INFO    MainThread:245296 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7efd5218ae10>
2021-09-22 00:18:29,923 INFO    MainThread:245296 [wandb_init.py:init():375] calling init triggers
2021-09-22 00:18:29,923 INFO    MainThread:245296 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-09-22 00:18:29,923 INFO    MainThread:245296 [wandb_init.py:init():424] starting backend
2021-09-22 00:18:29,923 INFO    MainThread:245296 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-22 00:18:30,090 INFO    MainThread:245296 [backend.py:ensure_launched():135] starting backend process...
2021-09-22 00:18:30,121 INFO    MainThread:245296 [backend.py:ensure_launched():140] started backend process with pid: 245715
2021-09-22 00:18:30,122 INFO    MainThread:245296 [wandb_init.py:init():429] backend started and connected
2021-09-22 00:18:30,140 INFO    MainThread:245296 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-22 00:18:30,141 INFO    MainThread:245296 [wandb_init.py:init():477] updated telemetry
2021-09-22 00:18:30,141 INFO    MainThread:245296 [wandb_init.py:init():500] communicating current version
2021-09-22 00:18:31,051 INFO    MainThread:245296 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-22 00:18:31,051 INFO    MainThread:245296 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-22 00:18:31,623 INFO    MainThread:245296 [wandb_init.py:init():540] starting run threads in backend
2021-09-22 00:18:36,629 INFO    MainThread:245296 [wandb_run.py:_console_start():1601] atexit reg
2021-09-22 00:18:36,629 INFO    MainThread:245296 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-22 00:18:36,630 INFO    MainThread:245296 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-22 00:18:36,630 INFO    MainThread:245296 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-22 00:18:36,631 INFO    MainThread:245296 [wandb_init.py:init():565] run started, returning control to user process
2021-09-22 00:19:09,836 INFO    MainThread:245296 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-22 00:19:09,836 INFO    MainThread:245296 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-09-22 00:19:10,324 INFO    MainThread:245296 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7efd51f11d90>
2021-09-22 00:19:30,401 INFO    MainThread:245296 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-22 00:19:30,401 INFO    MainThread:245296 [wandb_run.py:_restore():1543] restore
2021-09-22 00:19:31,780 INFO    MainThread:245296 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 8835
  total_bytes: 8835
}

2021-09-22 00:19:32,680 INFO    MainThread:245296 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 8835
  total_bytes: 32401
}

2021-09-22 00:19:32,783 INFO    MainThread:245296 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 8835
  total_bytes: 32401
}

2021-09-22 00:19:32,884 INFO    MainThread:245296 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 8835
  total_bytes: 32401
}

